healthcare_critical:
  alpha: 0.1
  beta: 0.8
  gamma: 0.1

industrial_high_throughput:
  alpha: 0.2
  beta: 0.3
  gamma: 0.5

smart_city_budget:
  alpha: 0.9
  beta: 0.05
  gamma: 0.05

balanced:
  alpha: 0.33
  beta: 0.33
  gamma: 0.33
